name: plantify
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_riverpod: ^2.4.4
  go_router: ^12.0.0
  riverpod_annotation: ^2.2.1

dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0-dev.5
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true
